app/loader/forms.py
# app/admin/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DateField, DateTimeField, SelectField
from wtforms.validators import DataRequired
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from ..models import Package


class PackageForm(FlaskForm):
    """
    Form for admin to add or edit a department
    """
    name = StringField('Name', validators=[DataRequired()])
    date_created = StringField('Date Created', validators=[DataRequired()])
    date_to_deliver = StringField('Date To Deliver', validators=[DataRequired()])
    addressed_to = StringField('Addressed To', validators=[DataRequired()])
    package_type = SelectField('Package Type', [DataRequired()],
                        choices=[('Roll Container', 'Roll Container'),
                                 ('Box', 'Box'),('Pallette','Pallette')
                                 ])
    hub = StringField('Hub', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    submit = SubmitField('Submit')


class LoaderAssignForm(FlaskForm):
    """
    Form for admin to assign departments and roles to employees
    """
    package = QuerySelectField(query_factory=lambda: Package.query.all(),
                                  get_label="name")
    # role = QuerySelectField(query_factory=lambda: Role.query.all(),
    #                         get_label="name")
    submit = SubmitField('Submit')

app/loader/__init__.py
# app/admin/__init__.py

from flask import Blueprint

loader = Blueprint('loader', __name__)




from . import views

app/loader/views.py
# app/admin/views.py

from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import loader
# from . forms import PackageForm
from .. import db
# from ..models import Package

from . forms import PackageForm, LoaderAssignForm
from ..models import Package, User


def check_loader():
    """
    Prevent non-admins from accessing the page
    """
    if not current_user.is_loader:

        abort(403)

# Department Views


@loader.route('/packages', methods=['GET', 'POST'])
@login_required
def list_packages():
    """
    List all packages
    """
    check_loader()

    packages = Package.query.all()

    return render_template('loader/packages/packages.html',
                           packages=packages, title="Packages")


@loader.route('/packages/add', methods=['GET', 'POST'])
@login_required
def add_package():
    """
     Add a package to the database
    """
    check_loader()

    add_package = True

    form = PackageForm()
    if form.validate_on_submit():
        package = Package(name=form.name.data, date_created = form.date_created.data, date_to_deliver = form.date_to_deliver.data,
        addressed_to = form.addressed_to.data, package_type = form.package_type.data, hub = form.hub.data,
                                description=form.description.data,)
        # try:
            # add department to the database
        db.session.add(package)
        db.session.commit()
        flash('You have successfully added a new package.')
        # except:
            # in case department name already exists
            # flash('Error: package name already exists.')

        # redirect to departments page
        return redirect(url_for('loader.list_packages'))

    # load department template
    return render_template('loader/packages/package.html', action="Add",
                           add_package=add_package, form=form,
                           title="Add Package")


@loader.route('/packages/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_package(id):
    """
    Edit a package
    """
    check_laoder()

    add_package = False

    package = Package.query.get_or_404(id)
    form = PackageForm(obj=package)
    if form.validate_on_submit():
        package.name = form.name.data
        package.date_created = form.date_created.data
        package.date_to_deliver = form.date_to_deliver.data
        package.addressed_to = form.addressed_to.data
        package.package_type = form.package_type.data
        package.hub = form.hub.data
        package.description = form.description.data
        db.session.commit()
        flash('You have successfully edited the package.')

        # redirect to the departments page
        return redirect(url_for('loader.list_packages'))

    
    form.name.data = package.name
    form.date_created.data = package.date_created
    form.date_to_deliver.data = package.date_to_deliver
    form.addressed_to.data = package.addressed_to
    form.package_type.data = package.package_type
    form.hub.data = package.hub
    form.description.data = package.description
    return render_template('loader/packages/package.html', action="Edit",
                           add_package=add_package, form=form,
                           package=package, title="Edit Package")


@loader.route('/packages/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_package(id):
    """
    Delete a package from the database
    """
    check_loader()

    package = Package.query.get_or_404(id)
    db.session.delete(package)
    db.session.commit()
    flash('You have successfully deleted the package.')

    # redirect to the departments page
    return redirect(url_for('loader.list_packages'))

    return render_template(title="Delete Package")  



# Loader Views

@loader.route('/loaders')
@login_required
def list_loaders():
    """
    List all employees
    """
    check_loader()

    loaders = User.query.all()
    return render_template('loader/loaders/loaders.html',
                           loaders=loaders, title='Loaders')


@loader.route('/loaders/assign/<int:id>', methods=['GET', 'POST'])
@login_required
def assign_loaders(id):
    """
    Assign a department and a role to an employee
    """
    check_loader()

    loader = User.query.get_or_404(id)

    # prevent admin from being assigned a department or role
    if loader.is_admin:
        abort(403)
    elif loader.is_supplier:
        abort(403)

    


    form = LoaderAssignForm(obj=loader)
    if form.validate_on_submit():
        loader.package = form.package.data 
        
        db.session.add(loader)
        db.session.commit()
        flash('You have successfully assigned a package.')

        # redirect to the roles page
        return redirect(url_for('loader.list_loaders'))

    return render_template('loader/loaders/loader.html',
                           loader=loader, form=form,
                           title='Assign Loader')

app/templates/loader/loaders/loader.html
<!-- app/templates/admin/employees/employee.html -->

{% import "bootstrap/wtf.html" as wtf %}
{% extends "loaderbase.html" %}
{% block title %}Assign Loader{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            <h1> Assign Package </h1>
            <br/>
            <p>
                Select a package to assign to
                <span style="color: #aec251;">
                    {{ loader.first_name }} {{ loader.last_name }}
                </span>
            </p>
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/loader/loaders/loaders.html
<!-- app/templates/admin/employees/employees.html -->

{% import "bootstrap/utils.html" as utils %}
{% extends "loaderbase.html" %}
{% block title %}Loaders{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Loaders</h1>
        {% if loaders %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                        <th width="15%"> Name </th>
                        <th width="30%"> Package </th>
                        
                        <th width="15%"> Assign </th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for loader in loaders %}
                      {% if loader.is_loader %}
                          
                      {% else %}
                          <tr>
                            <td> {{ loader.first_name }} {{ loader.last_name }} </td>
                            <td>
                              {% if loader.package %}
                                {{ loader.package.name }}
                                {% else %}
                                -
                              {% endif %}
                            </td>
                           
                            <td>
                              <a href="{{ url_for('loader.assign_loaders', id=loader.id) }}">
                                <i class="fa fa-user-plus"></i> Assign
                              </a>
                            </td>
                          </tr>
                      {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
          {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}